In [1]:
import numpy as np # linear algebra
import pandas as pd

In [4]:
import os
for dirname, _, filenames in os.walk('/content/Churn_Modelling.csv'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


In [5]:
Dataset = pd.read_csv('/content/Churn_Modelling.csv')

In [6]:
Dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
Dataset.Exited.value_counts()/len(Dataset)*100

Exited
0    79.63
1    20.37
Name: count, dtype: float64

In [9]:
x = Dataset.drop(['RowNumber','CustomerId','Surname','Exited'],axis=1)

In [10]:
x.head(2)

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619    France  Female   42       2      0.00              1   
1          608     Spain  Female   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58

In [11]:
y = Dataset.Exited.values

In [12]:
y


array([1, 0, 1, ..., 1, 1, 0])

In [13]:
x = pd.get_dummies(x,columns=['Geography','Gender'],drop_first=True)

In [14]:
x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0               1        101348.88              False            False   
1               1        112542.58              False             True   
2               0        113931.57              False            False   
3               0         93826.63              False            False   
4               1         79084.10              False             True   

   Gender_Male  
0        False  
1        False  
2        False  
3        False  
4        False

In [15]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [16]:
len(x_train)

7500

In [17]:
len(x_test)

2500

In [18]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

In [19]:
x_train_sc

array([[ 7.52887186e-01, -7.63285816e-01,  1.38007637e-04, ...,
        -5.82071790e-01, -5.67906748e-01,  9.13830871e-01],
       [ 1.04134287e+00, -6.67720592e-01,  1.38021438e+00, ...,
         1.71800114e+00, -5.67906748e-01,  9.13830871e-01],
       [ 1.95821986e+00,  1.24358389e+00,  1.38007637e-04, ...,
        -5.82071790e-01, -5.67906748e-01, -1.09429439e+00],
       ...,
       [ 1.34767868e-01,  1.72141001e+00,  3.45157100e-01, ...,
        -5.82071790e-01, -5.67906748e-01,  9.13830871e-01],
       [ 2.05093775e+00, -2.85459695e-01,  3.45157100e-01, ...,
        -5.82071790e-01, -5.67906748e-01, -1.09429439e+00],
       [ 2.05093775e+00,  9.68012010e-02,  3.45157100e-01, ...,
        -5.82071790e-01, -5.67906748e-01,  9.13830871e-01]])

In [20]:
x_test_sc

array([[ 2.05093775e+00,  1.23597690e-03,  3.45157100e-01, ...,
        -5.82071790e-01,  1.76085247e+00,  9.13830871e-01],
       [ 1.01043690e+00, -1.89894471e-01,  1.72523347e+00, ...,
        -5.82071790e-01, -5.67906748e-01,  9.13830871e-01],
       [ 8.76511050e-01, -9.54416264e-01,  1.38021438e+00, ...,
        -5.82071790e-01, -5.67906748e-01, -1.09429439e+00],
       ...,
       [-4.03659387e-02,  1.14801867e+00, -3.44881084e-01, ...,
         1.71800114e+00, -5.67906748e-01,  9.13830871e-01],
       [-2.67009689e-01, -6.67720592e-01,  6.90176192e-01, ...,
        -5.82071790e-01,  1.76085247e+00,  9.13830871e-01],
       [-1.25600060e+00, -8.58851040e-01, -1.03491927e+00, ...,
        -5.82071790e-01, -5.67906748e-01,  9.13830871e-01]])

In [21]:
from sklearn.ensemble import RandomForestClassifier

model  = RandomForestClassifier(n_estimators=100)

model.fit(x_train_sc,y_train)

RandomForestClassifier()

In [22]:
y_pred = model.predict(x_test_sc)

In [23]:
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [24]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred,y_test)*100)

86.56
